# Generated by Django 2.2.17 on 2020-12-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default='Mate', max_length=50),
            preserve_default=False,
        ),
    ]
