# Generated by Django 2.2.17 on 2020-12-14 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Curso', to='registro.Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='estudiate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Estudiante', to='registro.Estudiante'),
            preserve_default=False,
        ),
    ]
