# Generated by Django 2.2.17 on 2020-12-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20201213_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='cod',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
    ]
