# Generated by Django 2.2.17 on 2020-12-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_asignacion_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='nota',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
